name: .NET Core CI

on: [push]

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - name: Setup .NET if needed
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.401
      if: matrix.os == 'ubuntu-latest'
    - uses: actions/checkout@v3
    - name: Build
      run: dotnet build ./NumberToWords.sln --configuration Release
    - name: Test
      run: dotnet test ./NumberToWords.sln --configuration Release
    - name: Pack
      run: dotnet pack -c Release --no-build -o ./packages
    - name: Push
      run: dotnet nuget push ./packages/Number2Words.*.nupkg --skip-duplicate --api-key ${{secrets.NUGET_TOKEN}} --source https://api.nuget.org/v3/index.json
